-- LeadFlow AI — Website Form message (Form Message micro-phase)
--
-- Adds the only channel through which an inbound lead can state intent.
--
-- WHY: the AI qualification prompt grades five criteria, two of which —
-- Intent and Buying signals — had no input whatsoever. Measured twice against
-- the real pipeline, the model itself named the gap: "no stated need,
-- timeline, or request. No phone and no form message provided." A lead with
-- perfect firmographics (Apollo.io, 603 employees, US) still scored 38,
-- because the prompt correctly refuses to invent an intention nobody stated.
-- Nullable, because a form that collects no message, a webhook source, and
-- every manual/CSV lead all legitimately have none. RLS is untouched: `leads`
-- keeps its existing ENABLE + FORCE ROW LEVEL SECURITY and tenant policy, and
-- a column addition changes nothing about row visibility.
ALTER TABLE "leads" ADD COLUMN "formMessage" TEXT;
